### ISSUE TITLE
Fresh clone wont load homepage

### ISSUE THREAD

**Issue by thecrazytech1** [SonMooSans/discord-bot-dashboard-2#4]
**Describe the bug**
>When going to localhost:3000, it had the loading icon and then "Failed to login"
>and then the button with "try agian"

**To Reproduce**
1. Go to 'localhost:3000'
2. See error

**Expected behavior**
> to go to the main home page

**Screenshots**
![image](https://user-images.githubusercontent.com/69059820/209628308-8eda6cf4-fcdc-4af4-8573-af42d1ce077b.png)

**Device:**
 - OS: Windows
 - Browser: Opera
 - Version: latest

**Additional context**
N/A

**Comment by fuma-nama** [comment]
Please read the Guide carefully, You need to write a **backend** so that the dashboard can connect to your bot
I had wrote a document about it already

**Comment by thecrazytech1** [comment]
> 

Ohhhhh, I didn't see that part, thanks

**Comment by 8awv** [comment]
and how can i write a backend? i didn't understand these examples :<

**Comment by fuma-nama** [comment]
> and how can i write a backend? i didn't understand these examples :<

Oops! I'm sorry to hear that

You can try my [typescript backend](https://github.com/SonMooSans/discord-bot-dashboard-backend-ts) which supports launching without extra setup
Don't worry if it's too hard for you, A better version is now in development: https://github.com/SonMooSans/discord-bot-dashboard-next

**Comment by 8awv** [comment]
Thank you! Should I just clone it only?

**Comment by 8awv** [comment]
Because there's error, and the website isn't deploying

**Comment by 8awv** [comment]
Ugh, I've tried many times, I can't do it :<. I'm running it on replit. May you do it for me? the host is 0.0.0.0 :>

**Comment by fuma-nama** [comment]
> Because there's error, and the website isn't deploying

Can you give me more details?
It has been tested on Vercel & Railway, don't sure how is it on Replit
The website should be able to deploy to anywhere since it's a static site after building it

**Comment by 8awv** [comment]
It is deploying! but there's no index on the website, or a land page as they said.

**Comment by 8awv** [comment]
![image](https://user-images.githubusercontent.com/126328551/221795762-e6fff8b5-b902-4d7f-8afe-ed823d5b436b.png)

here's the output

**Comment by 8awv** [comment]
![image](https://user-images.githubusercontent.com/126328551/221796681-676e395d-2326-4f57-b3e2-7879241d235b.png)

New error...., where can i add the client id? and how can i make the auth for a certain website uri, bcz he's doing localhost

**Comment by 8awv** [comment]
What I mean here, he's redirecting to localhost, and I want it to a certain website, and the client id is not on the link

**Comment by 8awv** [comment]
![image](https://user-images.githubusercontent.com/126328551/221805866-7fa44eeb-3427-4fd7-9ed6-1d2a615dcbff.png)


Ok I've tried to make my own link that redirects to the website, and here's a new new error xD !

**Comment by fuma-nama** [comment]
> ![image](https://user-images.githubusercontent.com/126328551/221805866-7fa44eeb-3427-4fd7-9ed6-1d2a615dcbff.png)
> 
> 
> 
> 
> 
> Ok I've tried to make my own link that redirects to the website, and here's a new new error xD !
> 
> 

Failed to do OAuth2 request, have you filled the `BOT_CLIENT_ID` and `BOT_CLIENT_SECRET` environment variables correctly?

Please read the guide before asking a question

**Comment by fuma-nama** [comment]
Please open a new issue if you want to ask something
